name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test (Python ${{ matrix.python-version }})
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        include:
          - python-version: "3.10"
            toxenv: py310
          - python-version: "3.11"
            toxenv: py311
          - python-version: "3.12"
            toxenv: py312
          - python-version: "3.13"
            toxenv: py313
          - python-version: "3.14"
            toxenv: py314

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true

      - name: Install tox
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Run tests
        run: tox -e ${{ matrix.toxenv }}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          fail_ci_if_error: false
          flags: unittests
          name: codecov-coverage

  quality:
    name: Code Quality & Security
    runs-on: ubuntu-22.04
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install tox
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Run linting
        run: |
          echo "🔍 Running linting with tox..."
          tox -e lint
